### ISSUE TITLE
Image from camera doesn't scale properly

### ISSUE THREAD

**Issue by ptsimpso** [lucasecf/LECropPictureViewController#4] opened 2015-07-25 16:22 UTC
If I use a UIImagePicker with .sourceType = .Camera, the resulting image in the LECropPictureViewController is incredibly thing and not scaled properly. Everything works totally fine with when the image is gathered from .sourceType = .PhotoLibrary. My didFinishPickingMediaWithInfo: method is below (in Swift):

```
func imagePickerController(picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [NSObject : AnyObject]) {
    println(info)
    let originalImage = info[UIImagePickerControllerOriginalImage] as! UIImage

    let cropController = LECropPictureViewController(image: originalImage, andCropPictureType: LECropPictureType.Rounded)
    cropController.imageView.contentMode = UIViewContentMode.ScaleAspectFit

    cropController.photoAcceptedBlock = { (croppedImage: UIImage!) -> Void in
        let scaledImage = self.scaleImage(croppedImage, size: 300.0)
        let thumbnailImage = self.scaleImage(croppedImage, size: 100.0)

        self.profPic = scaledImage
        self.thumbnail = thumbnailImage
        self.refreshImageView(self.profPic!)

        picker.dismissViewControllerAnimated(true, completion: nil)
    }

    picker.pushViewController(cropController, animated: true)

}
```

**Comment by lucasecf** [comment] 2015-07-27 11:24
Hello @ptsimpso ,

Are you sure the problem is inside the `LECropPictureViewController` and not somewhere else? The component simply use any UIImage, regardless of where it came from.

Try to use the controller without using your `self.scaleImage` method, to see if your problem persists.

**Comment by ptsimpso** [comment] 2015-07-27 15:10
Problem is the same without my `scaleImage` function, which makes sense because the `scaleImage` function is not called until after your `photoAcceptedBlock` is invoked which is after the pic is displayed in your controller. Yeah, it's strange because this is just a normal UIImage gathered straight from the UIImagePicker's callback. I'm not messing with it in any way.

Are you able to reproduce if you do it from your phone?

What's interesting, is that the issue disappears if the LECropController's `imageView.backgroundColor` property is set. Issue only appears when that property is not set. It's pretty easy to just set the background color to black to mimic the default appearance, so this is a pretty low priority issue.

**Comment by lucasecf** [comment] 2015-07-31 12:35
@ptsimpso No, I could not reproduce this. Maybe it was fixed in the last PR, when the default contentMode was set to `UIViewContentModeScaleAspectFit`. Try to use the latest version and see if the problem persists

```
pod 'LECropPictureViewController', :git => 'https://github.com/lucasecf/LECropPictureViewController.git'
```

**Comment by addisonwebb** [comment] 2015-08-20 18:19
This is still an issue. Photos in portrait orientation still get stretched. Setting the imageView.backgroundColor does provide a decent workaround to the problem. I was only able to reproduce the issue on a device and not through the simulator.

**Comment by lucasecf** [comment] 2015-08-20 18:29
@addisonwebb Did you tried with the latest version from git (using the ":git => url-here" in Podfile)? If yes, can you give more informations, like XCode version and the device iOS version?

thanks,

**Comment by addisonwebb** [comment] 2015-08-20 18:44
Yes, I did try using `pod 'LECropPictureViewController', :git => 'https://github.com/lucasecf/LECropPictureViewController.git'` in the Podfile. No luck.

Device: iPhone 5s, iOS 8.4.1
Xcode: 6.4 (6E35b)

![img_0784](https://cloud.githubusercontent.com/assets/3932168/9392285/d8f502a8-4749-11e5-901f-6d3e46475731.jpg)

**Comment by lucasecf** [comment] 2015-08-20 19:23
Ok, I'll try to take a look as soon as possible

**Comment by lucasecf** [comment] 2015-09-24 13:38
@addisonwebb and @ptsimpso 

I tried again to reproduce this bug with a basic example,  in portrait, with the camera of the device and everything else, but with no success.

Maybe it's something specific for the view hierarchy you used? Can you guys provide a small project that shows this bug? Or even a full steps to reproduce it?

**Comment by lucasecf** [comment] 2015-10-13 19:02
I'm closing this issue because I wasn't able to reproduce and due the lack of informations. Please, if anyone see this again, give some feedback providing a small project or full steps to reproduce it.

**Closed as completed by lucasecf** 2015-10-13 19:02 UTC
